/**
 *  This file is automatically generated by PolySA CodeGen.
 *  Version: 1.0
 *  Authos: Jie Wang
 */

#include "common_header_U1.h"

void systolic_array_kernel(
  U1_bus_t0* global_A,
  U1_bus_t1* global_B,
  U1_bus_t2* global_C,
  bool init,
  unsigned int FILTER_S
){
#pragma HLS INTERFACE m_axi port=global_A offset=slave bundle=gmem0 depth=1024
#pragma HLS INTERFACE m_axi port=global_B offset=slave bundle=gmem1 depth=1024
#pragma HLS INTERFACE m_axi port=global_C offset=slave bundle=gmem2 depth=1024
#pragma HLS INTERFACE s_axilite port=global_A bundle=control
#pragma HLS INTERFACE s_axilite port=global_B bundle=control
#pragma HLS INTERFACE s_axilite port=global_C bundle=control
#pragma HLS INTERFACE s_axilite port=init bundle=control
#pragma HLS INTERFACE s_axilite port=FILTER_S bundle=control
#pragma HLS INTERFACE s_axilite port=return bundle=control

  U1_kernel(global_A, global_B, global_C, init, FILTER_S);
}
